### ISSUE TITLE
Implement application monitoring with Grafana and Prometheus

### ISSUE THREAD

**Issue by nottaras** [nottaras/prototype#3]
Copy from compose.yml of the previous project:

```
  prometheus:
    image: prom/prometheus
    depends_on:
      - app
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/main.yml
      - ./monitoring/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards

```

Files are located in the following path: `/Users/taras/Library/Mobile Documents/com~apple~CloudDocs/PARA/1 Projects/Prototype/monitoring`
