### ISSUE TITLE
Add MongoDB for file storage

### ISSUE THREAD

**Issue by nottaras** [nottaras/prototype#4]
Copy from compose.yml file of the previous project:
```
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: habitordie
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/
      ME_CONFIG_BASICAUTH: false

```

The implementation of the storage is located here: `/Users/taras/Library/Mobile Documents/com~apple~CloudDocs/PARA/1 Projects/Prototype/storage`.
